import type { PartOfSpeech } from '../types/toolbox';

export type RecommendationTier = 1 | 2 | 3;

export interface ToolboxRecommendationCandidate {
  lemma: string;
  surface: string;
  meaning: string;
  partOfSpeech: PartOfSpeech;
  example: string;
  tier: RecommendationTier;
}

/** Curated stretch words — tiered and spread across grammatical functions. */
export const TOOLBOX_RECOMMENDATION_POOL: ToolboxRecommendationCandidate[] = [
  // Tier 1 — essentials
  { lemma: 'bonjour', surface: 'bonjour', meaning: 'hello / good day', partOfSpeech: 'Expressions', example: 'Bonjour, comment ça va ?', tier: 1 },
  { lemma: 'merci', surface: 'merci', meaning: 'thank you', partOfSpeech: 'Expressions', example: 'Merci beaucoup !', tier: 1 },
  { lemma: 'manger', surface: 'manger', meaning: 'to eat', partOfSpeech: 'Verbs', example: 'Je mange une pomme.', tier: 1 },
  { lemma: 'maison', surface: 'maison', meaning: 'house / home', partOfSpeech: 'Nouns', example: 'Je rentre à la maison.', tier: 1 },
  { lemma: 'grand', surface: 'grand', meaning: 'big / tall', partOfSpeech: 'Adjectives', example: 'C\'est un grand parc.', tier: 1 },
  { lemma: 'très', surface: 'très', meaning: 'very', partOfSpeech: 'Adverbs', example: 'Il fait très froid.', tier: 1 },
  { lemma: 'je', surface: 'je', meaning: 'I', partOfSpeech: 'Pronouns', example: 'Je suis prêt.', tier: 1 },
  { lemma: 'le', surface: 'le', meaning: 'the (masculine)', partOfSpeech: 'Articles / Determiners', example: 'Le chat dort.', tier: 1 },
  { lemma: 'un', surface: 'un', meaning: 'a / one', partOfSpeech: 'Articles / Determiners', example: 'J\'ai un livre.', tier: 1 },
  { lemma: 'avec', surface: 'avec', meaning: 'with', partOfSpeech: 'Prepositions', example: 'Je viens avec toi.', tier: 1 },
  { lemma: 'et', surface: 'et', meaning: 'and', partOfSpeech: 'Conjunctions', example: 'Du pain et du fromage.', tier: 1 },
  { lemma: 'pas', surface: 'pas', meaning: 'not (negation)', partOfSpeech: 'Negation Particles', example: 'Je ne sais pas.', tier: 1 },
  { lemma: 'se', surface: 'se', meaning: 'oneself (reflexive)', partOfSpeech: 'Reflexive Pronouns', example: 'Il se lève tôt.', tier: 1 },

  // Tier 2 — expanding
  { lemma: 'réserver', surface: 'réserver', meaning: 'to book / reserve', partOfSpeech: 'Verbs', example: 'Je voudrais réserver une table.', tier: 2 },
  { lemma: 'travail', surface: 'travail', meaning: 'work (noun)', partOfSpeech: 'Nouns', example: 'Mon travail est intéressant.', tier: 2 },
  { lemma: 'important', surface: 'important', meaning: 'important', partOfSpeech: 'Adjectives', example: 'C\'est une décision importante.', tier: 2 },
  { lemma: 'souvent', surface: 'souvent', meaning: 'often', partOfSpeech: 'Adverbs', example: 'Je vais souvent au cinéma.', tier: 2 },
  { lemma: 'nous', surface: 'nous', meaning: 'we', partOfSpeech: 'Pronouns', example: 'Nous partons demain.', tier: 2 },
  { lemma: 'cette', surface: 'cette', meaning: 'this (feminine)', partOfSpeech: 'Articles / Determiners', example: 'Cette idée me plaît.', tier: 2 },
  { lemma: 'pendant', surface: 'pendant', meaning: 'during / for', partOfSpeech: 'Prepositions', example: 'Pendant les vacances.', tier: 2 },
  { lemma: 'parce que', surface: 'parce que', meaning: 'because', partOfSpeech: 'Conjunctions', example: 'Je reste parce que je suis fatigué.', tier: 2 },
  { lemma: 'ne...pas', surface: 'ne...pas', meaning: 'not (negation frame)', partOfSpeech: 'Negation Particles', example: 'Je ne parle pas anglais.', tier: 2 },
  { lemma: 'me', surface: 'me', meaning: 'me (reflexive / object)', partOfSpeech: 'Reflexive Pronouns', example: 'Je me repose.', tier: 2 },
  { lemma: 's\'il vous plaît', surface: 's\'il vous plaît', meaning: 'please (formal)', partOfSpeech: 'Expressions', example: 'Un café, s\'il vous plaît.', tier: 2 },
  { lemma: 'chez', surface: 'chez', meaning: 'at someone\'s place', partOfSpeech: 'Prepositions', example: 'Je dîne chez mes parents.', tier: 2 },

  // Tier 3 — richer repertoire
  { lemma: 'entreprendre', surface: 'entreprendre', meaning: 'to undertake / start', partOfSpeech: 'Verbs', example: 'Elle veut entreprendre un projet.', tier: 3 },
  { lemma: 'opportunité', surface: 'opportunité', meaning: 'opportunity', partOfSpeech: 'Nouns', example: 'C\'est une belle opportunité.', tier: 3 },
  { lemma: 'considérable', surface: 'considérable', meaning: 'considerable / significant', partOfSpeech: 'Adjectives', example: 'Un progrès considérable.', tier: 3 },
  { lemma: 'néanmoins', surface: 'néanmoins', meaning: 'nevertheless', partOfSpeech: 'Adverbs', example: 'Il pleut ; néanmoins, nous sortons.', tier: 3 },
  { lemma: 'celui', surface: 'celui', meaning: 'the one (demonstrative)', partOfSpeech: 'Pronouns', example: 'Celui que j\'aime.', tier: 3 },
  { lemma: 'chaque', surface: 'chaque', meaning: 'each / every', partOfSpeech: 'Articles / Determiners', example: 'Chaque jour compte.', tier: 3 },
  { lemma: 'malgré', surface: 'malgré', meaning: 'despite', partOfSpeech: 'Prepositions', example: 'Malgré la pluie, il sourit.', tier: 3 },
  { lemma: 'bien que', surface: 'bien que', meaning: 'although', partOfSpeech: 'Conjunctions', example: 'Bien qu\'il soit tard, je lis.', tier: 3 },
  { lemma: 'jamais', surface: 'jamais', meaning: 'never', partOfSpeech: 'Negation Particles', example: 'Je n\'ai jamais visité Lyon.', tier: 3 },
  { lemma: 's\'y', surface: 's\'y', meaning: 'there (reflexive / locative)', partOfSpeech: 'Reflexive Pronouns', example: 'Il s\'y sent chez lui.', tier: 3 },
  { lemma: 'avoir l\'air', surface: 'avoir l\'air', meaning: 'to seem / look', partOfSpeech: 'Expressions', example: 'Tu as l\'air fatigué.', tier: 3 },
  { lemma: 'cependant', surface: 'cependant', meaning: 'however', partOfSpeech: 'Adverbs', example: 'C\'est difficile ; cependant, j\'essaie.', tier: 2 },
  { lemma: 'leur', surface: 'leur', meaning: 'their / to them', partOfSpeech: 'Pronouns', example: 'Je leur téléphone ce soir.', tier: 2 },
  { lemma: 'donc', surface: 'donc', meaning: 'therefore / so', partOfSpeech: 'Conjunctions', example: 'Il pleut, donc je reste.', tier: 2 },

  // Extra tier 1–2 picks so Grow Your Toolbox can always offer 10 fresh words
  { lemma: 'boire', surface: 'boire', meaning: 'to drink', partOfSpeech: 'Verbs', example: 'Je bois un café le matin.', tier: 1 },
  { lemma: 'parler', surface: 'parler', meaning: 'to speak', partOfSpeech: 'Verbs', example: 'Nous parlons français en classe.', tier: 1 },
  { lemma: 'aimer', surface: 'aimer', meaning: 'to like / love', partOfSpeech: 'Verbs', example: 'J\'aime cette chanson.', tier: 1 },
  { lemma: 'chat', surface: 'chat', meaning: 'cat', partOfSpeech: 'Nouns', example: 'Le chat dort sur le canapé.', tier: 1 },
  { lemma: 'livre', surface: 'livre', meaning: 'book', partOfSpeech: 'Nouns', example: 'Je lis un livre intéressant.', tier: 1 },
  { lemma: 'petit', surface: 'petit', meaning: 'small / little', partOfSpeech: 'Adjectives', example: 'C\'est un petit village.', tier: 1 },
  { lemma: 'bien', surface: 'bien', meaning: 'well / good', partOfSpeech: 'Adverbs', example: 'Elle chante très bien.', tier: 1 },
  { lemma: 'tu', surface: 'tu', meaning: 'you (informal)', partOfSpeech: 'Pronouns', example: 'Tu viens ce soir ?', tier: 1 },
  { lemma: 'la', surface: 'la', meaning: 'the (feminine)', partOfSpeech: 'Articles / Determiners', example: 'La porte est ouverte.', tier: 1 },
  { lemma: 'de', surface: 'de', meaning: 'of / from', partOfSpeech: 'Prepositions', example: 'Je viens de Lyon.', tier: 1 },
  { lemma: 'ou', surface: 'ou', meaning: 'or', partOfSpeech: 'Conjunctions', example: 'Thé ou café ?', tier: 1 },
  { lemma: 'plus', surface: 'plus', meaning: 'more / no longer', partOfSpeech: 'Negation Particles', example: 'Je n\'en veux plus.', tier: 1 },
  { lemma: 'moi', surface: 'moi', meaning: 'me (stressed)', partOfSpeech: 'Reflexive Pronouns', example: 'Il m\'a parlé à moi.', tier: 1 },
  { lemma: 'au revoir', surface: 'au revoir', meaning: 'goodbye', partOfSpeech: 'Expressions', example: 'Au revoir et à bientôt !', tier: 1 },
  { lemma: 'habiter', surface: 'habiter', meaning: 'to live (reside)', partOfSpeech: 'Verbs', example: 'J\'habite près de la gare.', tier: 2 },
  { lemma: 'travailler', surface: 'travailler', meaning: 'to work', partOfSpeech: 'Verbs', example: 'Je travaille à l\'hôpital.', tier: 2 },
  { lemma: 'école', surface: 'école', meaning: 'school', partOfSpeech: 'Nouns', example: 'Les enfants vont à l\'école.', tier: 2 },
  { lemma: 'heureux', surface: 'heureux', meaning: 'happy', partOfSpeech: 'Adjectives', example: 'Il est heureux aujourd\'hui.', tier: 2 },
  { lemma: 'demain', surface: 'demain', meaning: 'tomorrow', partOfSpeech: 'Adverbs', example: 'Nous partons demain matin.', tier: 2 },
  { lemma: 'vous', surface: 'vous', meaning: 'you (formal / plural)', partOfSpeech: 'Pronouns', example: 'Vous parlez français ?', tier: 2 },
  { lemma: 'des', surface: 'des', meaning: 'some (plural)', partOfSpeech: 'Articles / Determiners', example: 'J\'achète des pommes.', tier: 2 },
  { lemma: 'sans', surface: 'sans', meaning: 'without', partOfSpeech: 'Prepositions', example: 'Je bois du thé sans sucre.', tier: 2 },
  { lemma: 'mais', surface: 'mais', meaning: 'but', partOfSpeech: 'Conjunctions', example: 'Il est tard, mais je lis encore.', tier: 2 },
  { lemma: 'rien', surface: 'rien', meaning: 'nothing', partOfSpeech: 'Negation Particles', example: 'Je ne vois rien.', tier: 2 },
  { lemma: 'en', surface: 'en', meaning: 'of it / some', partOfSpeech: 'Reflexive Pronouns', example: 'J\'en ai besoin.', tier: 2 },
  { lemma: 'de rien', surface: 'de rien', meaning: 'you\'re welcome', partOfSpeech: 'Expressions', example: 'Merci ! — De rien.', tier: 2 },

  // More stretch words to keep 10 Grow slots available
  { lemma: 'mon', surface: 'mon', meaning: 'my (masculine)', partOfSpeech: 'Articles / Determiners', example: 'Mon frère habite à Lyon.', tier: 1 },
  { lemma: 'ma', surface: 'ma', meaning: 'my (feminine)', partOfSpeech: 'Articles / Determiners', example: 'Ma sœur travaille ici.', tier: 1 },
  { lemma: 'mes', surface: 'mes', meaning: 'my (plural)', partOfSpeech: 'Articles / Determiners', example: 'Mes parents arrivent demain.', tier: 1 },
  { lemma: 'ce', surface: 'ce', meaning: 'this (masculine)', partOfSpeech: 'Articles / Determiners', example: 'Ce livre est intéressant.', tier: 2 },
  { lemma: 'ces', surface: 'ces', meaning: 'these', partOfSpeech: 'Articles / Determiners', example: 'Ces enfants jouent dehors.', tier: 2 },
  { lemma: 'regarder', surface: 'regarder', meaning: 'to watch / look at', partOfSpeech: 'Verbs', example: 'Je regarde un film.', tier: 2 },
  { lemma: 'écrire', surface: 'écrire', meaning: 'to write', partOfSpeech: 'Verbs', example: 'J\'écris une lettre.', tier: 2 },
  { lemma: 'dormir', surface: 'dormir', meaning: 'to sleep', partOfSpeech: 'Verbs', example: 'Je dors huit heures.', tier: 2 },
  { lemma: 'fromage', surface: 'fromage', meaning: 'cheese', partOfSpeech: 'Nouns', example: 'J\'aime le fromage.', tier: 1 },
  { lemma: 'pain', surface: 'pain', meaning: 'bread', partOfSpeech: 'Nouns', example: 'Je mange du pain.', tier: 1 },
  { lemma: 'joli', surface: 'joli', meaning: 'pretty / nice', partOfSpeech: 'Adjectives', example: 'C\'est un joli jardin.', tier: 2 },
  { lemma: 'toujours', surface: 'toujours', meaning: 'always', partOfSpeech: 'Adverbs', example: 'Il est toujours ponctuel.', tier: 2 },
  { lemma: 'il', surface: 'il', meaning: 'he / it', partOfSpeech: 'Pronouns', example: 'Il parle français.', tier: 1 },
  { lemma: 'elle', surface: 'elle', meaning: 'she', partOfSpeech: 'Pronouns', example: 'Elle travaille ici.', tier: 1 },
  { lemma: 'les', surface: 'les', meaning: 'the (plural)', partOfSpeech: 'Articles / Determiners', example: 'Les enfants jouent.', tier: 1 },
  { lemma: 'sur', surface: 'sur', meaning: 'on / upon', partOfSpeech: 'Prepositions', example: 'Le chat est sur la table.', tier: 2 },
  { lemma: 'car', surface: 'car', meaning: 'because', partOfSpeech: 'Conjunctions', example: 'Je reste, car je suis fatigué.', tier: 2 },
  { lemma: 'personne', surface: 'personne', meaning: 'nobody', partOfSpeech: 'Negation Particles', example: 'Je ne vois personne.', tier: 2 },
  { lemma: 'te', surface: 'te', meaning: 'you (object)', partOfSpeech: 'Reflexive Pronouns', example: 'Je te téléphone.', tier: 2 },
  { lemma: 'comment', surface: 'comment', meaning: 'how', partOfSpeech: 'Adverbs', example: 'Comment ça va ?', tier: 1 },
  { lemma: 'beaucoup', surface: 'beaucoup', meaning: 'a lot', partOfSpeech: 'Adverbs', example: 'Merci beaucoup !', tier: 1 },

  // Extended pool — keeps Grow Your Toolbox at 10 even after many adds/skips
  { lemma: 'voir', surface: 'voir', meaning: 'to see', partOfSpeech: 'Verbs', example: 'Je vois la mer.', tier: 2 },
  { lemma: 'entendre', surface: 'entendre', meaning: 'to hear', partOfSpeech: 'Verbs', example: 'J\'entends de la musique.', tier: 2 },
  { lemma: 'acheter', surface: 'acheter', meaning: 'to buy', partOfSpeech: 'Verbs', example: 'J\'achète du pain.', tier: 2 },
  { lemma: 'vendre', surface: 'vendre', meaning: 'to sell', partOfSpeech: 'Verbs', example: 'Il vend des livres.', tier: 3 },
  { lemma: 'courir', surface: 'courir', meaning: 'to run', partOfSpeech: 'Verbs', example: 'Je cours le matin.', tier: 2 },
  { lemma: 'nager', surface: 'nager', meaning: 'to swim', partOfSpeech: 'Verbs', example: 'Nous nageons en été.', tier: 2 },
  { lemma: 'finir', surface: 'finir', meaning: 'to finish', partOfSpeech: 'Verbs', example: 'Je finis mon travail.', tier: 2 },
  { lemma: 'choisir', surface: 'choisir', meaning: 'to choose', partOfSpeech: 'Verbs', example: 'Tu choisis un dessert.', tier: 2 },
  { lemma: 'pomme', surface: 'pomme', meaning: 'apple', partOfSpeech: 'Nouns', example: 'Je mange une pomme.', tier: 1 },
  { lemma: 'café', surface: 'café', meaning: 'coffee / café', partOfSpeech: 'Nouns', example: 'Un café, s\'il vous plaît.', tier: 1 },
  { lemma: 'restaurant', surface: 'restaurant', meaning: 'restaurant', partOfSpeech: 'Nouns', example: 'Nous dînons au restaurant.', tier: 2 },
  { lemma: 'hôpital', surface: 'hôpital', meaning: 'hospital', partOfSpeech: 'Nouns', example: 'Il travaille à l\'hôpital.', tier: 2 },
  { lemma: 'ville', surface: 'ville', meaning: 'city', partOfSpeech: 'Nouns', example: 'Paris est une grande ville.', tier: 2 },
  { lemma: 'jardin', surface: 'jardin', meaning: 'garden', partOfSpeech: 'Nouns', example: 'Les fleurs du jardin sont belles.', tier: 2 },
  { lemma: 'jeune', surface: 'jeune', meaning: 'young', partOfSpeech: 'Adjectives', example: 'C\'est un jeune artiste.', tier: 2 },
  { lemma: 'vieux', surface: 'vieux', meaning: 'old', partOfSpeech: 'Adjectives', example: 'C\'est un vieux bâtiment.', tier: 2 },
  { lemma: 'facile', surface: 'facile', meaning: 'easy', partOfSpeech: 'Adjectives', example: 'C\'est une question facile.', tier: 2 },
  { lemma: 'difficile', surface: 'difficile', meaning: 'difficult', partOfSpeech: 'Adjectives', example: 'C\'est un exercice difficile.', tier: 2 },
  { lemma: 'vite', surface: 'vite', meaning: 'quickly', partOfSpeech: 'Adverbs', example: 'Il marche vite.', tier: 2 },
  { lemma: 'lentement', surface: 'lentement', meaning: 'slowly', partOfSpeech: 'Adverbs', example: 'Parle lentement, s\'il te plaît.', tier: 2 },
  { lemma: 'on', surface: 'on', meaning: 'one / we (informal)', partOfSpeech: 'Pronouns', example: 'On va au cinéma.', tier: 1 },
  { lemma: 'ils', surface: 'ils', meaning: 'they (masculine)', partOfSpeech: 'Pronouns', example: 'Ils arrivent demain.', tier: 1 },
  { lemma: 'son', surface: 'son', meaning: 'his / her (masculine)', partOfSpeech: 'Articles / Determiners', example: 'Son frère est médecin.', tier: 2 },
  { lemma: 'sa', surface: 'sa', meaning: 'his / her (feminine)', partOfSpeech: 'Articles / Determiners', example: 'Sa maison est grande.', tier: 2 },
  { lemma: 'ses', surface: 'ses', meaning: 'his / her (plural)', partOfSpeech: 'Articles / Determiners', example: 'Ses parents habitent ici.', tier: 2 },
  { lemma: 'cet', surface: 'cet', meaning: 'this (masculine, before vowel)', partOfSpeech: 'Articles / Determiners', example: 'Cet homme est gentil.', tier: 2 },
  { lemma: 'dans', surface: 'dans', meaning: 'in / into', partOfSpeech: 'Prepositions', example: 'Le chat est dans la maison.', tier: 1 },
  { lemma: 'pour', surface: 'pour', meaning: 'for', partOfSpeech: 'Prepositions', example: 'Ce cadeau est pour toi.', tier: 1 },
  { lemma: 'entre', surface: 'entre', meaning: 'between', partOfSpeech: 'Prepositions', example: 'Entre toi et moi.', tier: 2 },
  { lemma: 'quand', surface: 'quand', meaning: 'when', partOfSpeech: 'Conjunctions', example: 'Quand tu viens ?', tier: 2 },
  { lemma: 'si', surface: 'si', meaning: 'if', partOfSpeech: 'Conjunctions', example: 'Si tu veux, on sort.', tier: 2 },
  { lemma: 'ni', surface: 'ni', meaning: 'neither / nor', partOfSpeech: 'Negation Particles', example: 'Je ne mange ni viande ni poisson.', tier: 3 },
  { lemma: 'ton', surface: 'ton', meaning: 'your (masculine)', partOfSpeech: 'Articles / Determiners', example: 'Ton chat est mignon.', tier: 2 },
  { lemma: 'ta', surface: 'ta', meaning: 'your (feminine)', partOfSpeech: 'Articles / Determiners', example: 'Ta voiture est neuve.', tier: 2 },
  { lemma: 'excusez-moi', surface: 'excusez-moi', meaning: 'excuse me', partOfSpeech: 'Expressions', example: 'Excusez-moi, où est la gare ?', tier: 2 },
  { lemma: 'à bientôt', surface: 'à bientôt', meaning: 'see you soon', partOfSpeech: 'Expressions', example: 'À bientôt !', tier: 2 },
  { lemma: 'santé', surface: 'santé', meaning: 'health', partOfSpeech: 'Nouns', example: 'La santé est importante.', tier: 3 },
  { lemma: 'problème', surface: 'problème', meaning: 'problem', partOfSpeech: 'Nouns', example: 'Ce n\'est pas un problème.', tier: 2 },
  { lemma: 'question', surface: 'question', meaning: 'question', partOfSpeech: 'Nouns', example: 'J\'ai une question.', tier: 2 },
  { lemma: 'réponse', surface: 'réponse', meaning: 'answer', partOfSpeech: 'Nouns', example: 'Quelle est la réponse ?', tier: 2 },
  { lemma: 'chaud', surface: 'chaud', meaning: 'hot / warm', partOfSpeech: 'Adjectives', example: 'Il fait chaud aujourd\'hui.', tier: 1 },
  { lemma: 'froid', surface: 'froid', meaning: 'cold', partOfSpeech: 'Adjectives', example: 'Il fait froid dehors.', tier: 1 },
  { lemma: 'maintenant', surface: 'maintenant', meaning: 'now', partOfSpeech: 'Adverbs', example: 'Je pars maintenant.', tier: 1 },
  { lemma: 'hier', surface: 'hier', meaning: 'yesterday', partOfSpeech: 'Adverbs', example: 'Hier, il a plu.', tier: 2 },
  { lemma: 'nos', surface: 'nos', meaning: 'our (plural)', partOfSpeech: 'Articles / Determiners', example: 'Nos voisins sont sympas.', tier: 2 },
  { lemma: 'sous', surface: 'sous', meaning: 'under', partOfSpeech: 'Prepositions', example: 'Le chat est sous la table.', tier: 2 },
  { lemma: 'avant', surface: 'avant', meaning: 'before', partOfSpeech: 'Prepositions', example: 'Avant le dîner.', tier: 2 },
  { lemma: 'après', surface: 'après', meaning: 'after', partOfSpeech: 'Prepositions', example: 'Après les cours.', tier: 2 },
  { lemma: 'pardon', surface: 'pardon', meaning: 'sorry / pardon', partOfSpeech: 'Expressions', example: 'Pardon, je ne comprends pas.', tier: 1 },
];
